### ISSUE TITLE
Nvidia Prime Passwordless Switch Between Intel & Nvidia GPUs

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/nvidia-prime#2]
Hi Dev Team,

Could you change following line (in usr/share/polkit-1/actions/screenresolution-mechanism.policy file),

from  **auth_admin_keep**

```
  <action id="com.ubuntu.screenresolution.mechanism.prime">
    <description>Enable or disable the NVIDIA GPU with PRIME</description>
    <message>Enabling or disabling the NVIDIA GPU requires privileges.</message>
    <defaults>
      <allow_inactive>no</allow_inactive>
      <allow_active>auth_admin_keep</allow_active>
    </defaults>
  </action>
```

to  **yes**

```
  <action id="com.ubuntu.screenresolution.mechanism.prime">
    <description>Enable or disable the NVIDIA GPU with PRIME</description>
    <message>Enabling or disabling the NVIDIA GPU requires privileges.</message>
    <defaults>
      <allow_inactive>no</allow_inactive>
      <allow_active>yes</allow_active>
    </defaults>
  </action>
```

for paswordless switch with Nvidia Prime. This file comes with screen-resolution-extra package.

@clefebvre

**Comment by clefebvre** [comment]
Hi,

Please make this request with Ubuntu.

**Comment by kelebek333** [comment]
I already can manually fix it. I want that get benefit other Linux Mint users. I do not care about Ubuntu.

**Comment by clefebvre** [comment]
By moving it upstream, it gets improved for everybody. Similarly Ubuntu might take ownership of it, or forward it to Debian, and then from there it might get upstream from them as well (I'm talking in general here). Next thing you know, it's not just fixed in Mint, but in Debian, Ubuntu, LMDE, and all other distributions.
